"""empty message

Revision ID: ae7dee623a9f
Revises: 
Create Date: 2019-08-12 14:02:20.862294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7dee623a9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=1000), nullable=True),
    sa.Column('Quantity', sa.String(length=1000), nullable=True),
    sa.Column('UserID', sa.String(length=128), nullable=True),
    sa.Column('Price', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menuid', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=1000), nullable=True),
    sa.Column('Img', sa.String(length=1000), nullable=True),
    sa.Column('Category', sa.String(length=1000), nullable=True),
    sa.Column('Tag', sa.String(length=128), nullable=True),
    sa.Column('Price', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('customerid', sa.String(length=1000), autoincrement=False, nullable=False),
    sa.Column('customername', sa.String(length=1000), nullable=True),
    sa.Column('customerclass', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('customerid')
    )
    op.create_table('vector',
    sa.Column('IDs', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=1000), nullable=True),
    sa.Column('v1', sa.Integer(), nullable=True),
    sa.Column('v2', sa.Integer(), nullable=True),
    sa.Column('v3', sa.Integer(), nullable=True),
    sa.Column('v4', sa.Integer(), nullable=True),
    sa.Column('v5', sa.Integer(), nullable=True),
    sa.Column('v6', sa.Integer(), nullable=True),
    sa.Column('v7', sa.Integer(), nullable=True),
    sa.Column('v8', sa.Integer(), nullable=True),
    sa.Column('v9', sa.Integer(), nullable=True),
    sa.Column('v10', sa.Integer(), nullable=True),
    sa.Column('v11', sa.Integer(), nullable=True),
    sa.Column('v12', sa.Integer(), nullable=True),
    sa.Column('v13', sa.Integer(), nullable=True),
    sa.Column('v14', sa.Integer(), nullable=True),
    sa.Column('v15', sa.Integer(), nullable=True),
    sa.Column('v16', sa.Integer(), nullable=True),
    sa.Column('v17', sa.Integer(), nullable=True),
    sa.Column('v18', sa.Integer(), nullable=True),
    sa.Column('v19', sa.Integer(), nullable=True),
    sa.Column('v20', sa.Integer(), nullable=True),
    sa.Column('v21', sa.Integer(), nullable=True),
    sa.Column('v22', sa.Integer(), nullable=True),
    sa.Column('v23', sa.Integer(), nullable=True),
    sa.Column('v24', sa.Integer(), nullable=True),
    sa.Column('v25', sa.Integer(), nullable=True),
    sa.Column('v26', sa.Integer(), nullable=True),
    sa.Column('v27', sa.Integer(), nullable=True),
    sa.Column('v28', sa.Integer(), nullable=True),
    sa.Column('v29', sa.Integer(), nullable=True),
    sa.Column('v30', sa.Integer(), nullable=True),
    sa.Column('v31', sa.Integer(), nullable=True),
    sa.Column('v32', sa.Integer(), nullable=True),
    sa.Column('v33', sa.Integer(), nullable=True),
    sa.Column('v34', sa.Integer(), nullable=True),
    sa.Column('v35', sa.Integer(), nullable=True),
    sa.Column('v36', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IDs')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector')
    op.drop_table('users')
    op.drop_table('product')
    op.drop_table('order')
    # ### end Alembic commands ###
